version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu

build_script:
  # on linux, it seems like msbuild goes parallel such that if we don't build ProcessSignaler first, we won't have the net45 binary
  # to pack into the non-net45 builds
  - dotnet build MedallionShell.ProcessSignaler/MedallionShell.ProcessSignaler.csproj -c Release
  - dotnet build MedallionShell.sln -c Release

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test MedallionShell.sln -c Release --no-build
  - 
    matrix: 
      only: 
        - 
          image: "Ubuntu"
    test_script:
      - dotnet test MedallionShell.sln -c Release -f net6.0 --no-build
      # test mono via the NUnit console runner
      - nuget install NUnit.Console -Version 3.16.3 -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json
      - mono ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net462/MedallionShell.Tests.dll